# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow get Pull request
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
   ######### Added by susanta to exclude path/file
   paths-ignore:
    - '.github/workflows/*.yml'
   branches: 
    - main
    ######### Added by susanta to exclude qc and ppd branch
    #- susgcit_qc
    #- susgcit_ppd
    
  push:
   ######### Added by susanta to exclude path/file
   paths-ignore:
    - '.github/workflows/*.yml'
   branches: 
    - main
    ######### Added by susanta to exclude qc and ppd branch
    - susgcit_qc
    - susgcit_ppd

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-QC-OtherApp:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #########added by Susanta conditional pull
    if: github.event_name == 'pull_request' && (github.ref_name != 'susgcit_qc' || github.ref_name != 'susgcit_ppd')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying to QC!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and Deploying to QC!!

# Controls when the workflow get push request

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel


  # This workflow contains a single job called "build"
  build-Prod:
    #needs: build-QC
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    ######## Added by susanta to run only if the merge from ppd branch
    if: github.event_name == 'push' && github.ref_name != 'susgcit_qc'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying to production!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and Deploying to production!!


  build-QC-GCIT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #########added by Susanta conditional pull
    if: github.event_name == 'push' && github.ref_name == 'susgcit_qc'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying to QC!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and Deploying to QC!!


  build-PPD-GCIT:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #########added by Susanta conditional pull
    if: github.event_name == 'push' && github.ref == 'susgcit_ppd'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploying to PPD!!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and Deploying to PPD!!
